CREATE TABLE [dbo].[Votes]
(
	[VoteInstanceID] UNIQUEIDENTIFIER NOT NULL, 
    [UserID] UNIQUEIDENTIFIER NOT NULL,
    [Vote] NVARCHAR(50) NOT NULL, 
    [VoteCreatedDate] DATETIME NOT NULL, 
    [VoteUpdatedDate] DATETIME NOT NULL, 
    CONSTRAINT [PK_Votes] PRIMARY KEY ([VoteInstanceID]),
    CONSTRAINT [FK_UserVote] FOREIGN KEY (UserID) REFERENCES Users(UserID)
)
